product: amzn2
full_name: Amazon Linux 2
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes_root: "../shared/applicability"
cpes:
  - amzn2:
      name: "cpe:/o:amzn:2"
      title: "Amazon Linux 2"
      check_id: installed_OS_is_amzn2